---
apiVersion: v2
name: additional-components
description: Provides a means of installing additional components for Grafana Cloud Collector
icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
version: 1.0.0
appVersion: 1.0.0
maintainers:
  - email: pete.wall@grafana.com
    name: petewall
dependencies:
  - name: kube-state-metrics
    version: 6.3.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-state-metrics.enabled
  - name: prometheus-node-exporter
    version: 4.47.3
    repository: https://prometheus-community.github.io/helm-charts
    condition: node-exporter.enabled
  - name: prometheus-windows-exporter
    version: 0.12.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: windows-exporter.enabled
  - name: kepler
    version: 0.6.1
    repository: https://sustainable-computing-io.github.io/kepler-helm-chart
    condition: kepler.enabled
  - name: opencost
    version: 2.2.7
    repository: https://opencost.github.io/opencost-helm-chart
    condition: opencost.enabled
