---
enable-beta-ecosystems: true  # Enables Helm dependency checking

version: 2
updates:
  - package-ecosystem: helm
    directory: /charts/grafana-cloud-onboarding
    schedule:
      interval: daily
    labels:
      - dependencies
      - helm
  - package-ecosystem: helm
    directory: /charts/grafana-cloud-onboarding/charts/additional-components
    schedule:
      interval: daily
    labels:
      - dependencies
      - helm
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - github-actions
