version: "3"

tasks:
  install-plugins:
    desc: Install required plugins
    cmds:
      - helm plugin install https://github.com/quintush/helm-unittest || echo "Plugin already installed, skipping."

  update-deps:
    desc: Update the dependencies
    dir: charts/grafana-cloud-collector
    cmds:
      - helm dependency update

  test:
    desc: Run all tests
    cmds:
      - task: unittest
      - task: test-golden-records

  unittest:
    desc: Run unit tests for the Helm chart
    cmds:
      - helm unittest charts/grafana-cloud-collector

  lint:
    desc: Lint the Helm chart
    cmds:
      - helm lint charts/grafana-cloud-collector

  generate:
    desc: Generate all the generated content
    cmds:
      - task: generate-golden-records

  generate-golden-records:
    desc: Generate golden record result files from values files
    cmds:
      - |
        set -e
        for values_file in charts/grafana-cloud-collector/tests/goldenrecords/*_values.yaml; do
          result_file="${values_file%_values.yaml}_result.yaml"
          echo "Generating $result_file from $values_file"
          helm template test ./charts/grafana-cloud-collector -f "$values_file" -n test-namespace > "$result_file"
        done

  test-golden-records:
    desc: Verify that generated golden records match existing ones
    cmds:
      - |
        set -e
        for values_file in charts/grafana-cloud-collector/tests/goldenrecords/*_values.yaml; do
          result_file="${values_file%_values.yaml}_result.yaml"
          temp_file=$(mktemp)
          
          echo "Verifying $result_file..."
          helm template test ./charts/grafana-cloud-collector -f "$values_file" -n test-namespace > "$temp_file"
          
          if ! diff -u "$result_file" "$temp_file"; then
            echo "Error: Generated content does not match golden record for $result_file"
            rm "$temp_file"
            exit 1
          fi
          
          rm "$temp_file"
        done
      - 'echo Test completed'
