{{- $remoteConfigValues := merge .Values.grafanaCloud.fleetManagement (dict "type" "fleetManagement" "name" "grafana-cloud-fleet-management") }}
{{- with $remoteConfigValues }}
{{- if eq (include "secrets.shouldCreateKubernetesSecret" . ) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.kubernetesSecretName" (deepCopy $ | merge (dict "object" .)) | quote }}
  namespace: {{ include "secrets.kubernetesSecretNamespace" (deepCopy $ | merge (dict "object" .)) | quote }}
type: Opaque
data:
{{- $secrets := include "secrets.list.fleetManagement" . | fromYamlArray }}
{{- range $secret := $secrets }}
  {{- $value := include "secrets.getSecretValue" (dict "object" $remoteConfigValues "key" $secret) -}}
  {{- if $value }}
  {{ include "secrets.getSecretKey" (dict "object" $remoteConfigValues "key" $secret) }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end -}}
{{- end -}}
