name: Run tests

on:
  pull_request:
    branches: [main]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: 'false'

      - name: Install Task
        uses: arduino/setup-task@43a9160573b9d326fe4cc7348a8e2b54e12ddd2a
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: task install-plugins test
