name: Run tests

on:
  pull_request:
    branches: [main]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: 'false'

      - name: Install Task
        uses: arduino/setup-task@27fc9a8d54e8bed4ad6a3e86cbc41c59323fc5f2
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: task install-plugins test
